---
title: "QTL Scanning"
author: "Matthew Gibson"
date: "June 8, 2017"
output:
  pdf_document: default
  html_document: default
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(qtl)
macDir <- "~/jaltomataQTL"
pcDir <- "c:/Users/matth/Documents/bin/jaltomataQTL/mapping_3"
karstDir <- "/N/u/gibsomat/Karst/thindrives/bin/jaltomataQTL/mapping_3"
setwd(pcDir)
```

## Load the cross
```{r}
mapJal5.1 <- read.cross("csv",pcDir, "final_map_6_15_t.csv", genotypes=c("A", "H"), alleles=c("A", "B"), na.strings=c("-", "NA"), estimate.map=F,crosstype = "bc")
write.cross(mapJal5.1, format="csvr")
plot.map(mapJal5.1)
mapJal5.1 <- calc.genoprob(mapJal5.1, step=0.1)
```

## Setup covariates
```{r}
bench <- pull.pheno(mapJal5.1, pheno.col = 3)
hmorph <- pull.pheno(mapJal5.1, pheno.col=c(3, 4))
fmorph <- pull.pheno(mapJal5.1, pheno.col=c(3, 5))
hcolor <- pull.pheno(mapJal5.1, pheno.col=c(3, 6))
fcolor <- pull.pheno(mapJal5.1, pheno.col=c(3, 7))
crossed <- pull.pheno(mapJal5.1, pheno.col=c(3, 8))
trichome <- pull.pheno(mapJal5.1, pheno.col=c(3,8))
veg <- pull.pheno(mapJal5.1, pheno.col=c(3, 10))
```

# Scan for QTL

```{r}
#all <- scanone(mapJal5.1, pheno.col=c(3:87))
#summary(all, threshold=3, format="tabByCol")
```

### Trichomes
```{r}
hairs <- scanone(mapJal5.1, pheno.col=11, method="em", model="binary",addcovar=trichome)
plot(hairs)
abline(3,0,lty=2)
```

### Seedling form and spacing
```{r}
formSpacing <- scanone(mapJal5.1, pheno.col=c(88,89), method="em", model="binary", addcovar=trichome)
plot(formSpacing, lodcolumn = 1)
abline(3,0,lty=2)

plot(formSpacing, lodcolumn = 2)
abline(3,0,lty=2)
```

### Vegetative traits
```{r}
vegScan <- scanone(mapJal5.1, pheno.col=c(12:17), method = "em", addcovar=veg)
for (x in 1:6){
  plot(vegScan, lodcolumn = x)
  abline(3,0,lty=2)
}
```

### Female morph
```{r}
femMorph <- scanone(mapJal5.1, pheno.col=c(18:28), method="em", addcovar=fmorph)
for (x in 1:11){
  plot(femMorph, lodcolumn = x)
  abline(3,0,lty=2)
}
```

### Herm morph
```{r}
hermMorph <- scanone(mapJal5.1, pheno.col=c(29:41), method="em", addcovar=hmorph)
for (x in 1:13){
  plot(hermMorph, lodcolumn = x)
  abline(3,0,lty=2)
}
```

### Female color
```{r}
femColor <- scanone(mapJal5.1, pheno.col=c(42:58), method="mr", addcovar=fcolor)
for (x in 1:17){
  plot(femColor, lodcolumn = x)
  abline(3,0,lty=2)
}
```

### Herm color

```{r}
hermColor <- scanone(mapJal5.1, pheno.col=c(59:75), method="em", addcovar=hcolor)
for (x in 1:17){
  plot(hermColor, lodcolumn = x)
  abline(3,0,lty=2)
}
```

### Fertility and fruit traits

```{r}
fertility <- scanone(mapJal5.1, pheno.col=c(76:87), method="em", addcovar=crossed)
for (x in 1:11){
  plot(fertility, lodcolumn = x)
  abline(3,0,lty=2)
}

```


## Permutation tests
```{r}
testPerm <- scanone(mapJal5.1, pheno.col=c(59), n.perm=5, addcovar = trichome)

out.hk <- scanone(mapJal5.1, pheno.col=59, method="hk")
summary(out.hk, perms=testPerm, alpha=0.05, pvalues=T)
x <- summary(testPerm)
save(x, file="x.data")

```